### ISSUE TITLE
problems when building the project. 

### ISSUE THREAD

**Issue by ghost** [STMicroelectronics/STBlueMS_Android#14]

**Comment by ghost** [comment]
when trying to build a project, the following error occurs:

```
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-29).
Dependency: androidx.core:core-ktx:1.8.0-alpha02.
AAR metadata file: C:\Users\ks-morozov\.gradle\caches\transforms-3\52bd9d9cc4c6efe2b509379bed7b6d31\transformed\jetified-core-ktx-1.8.0-alpha02\META-INF\com\android\build\gradle\aar-metadata.properties.
```

if I chang `compileSdkVersion = 29` to `compileSdkVersion = 31` on 'build.gradle' I get the following error:
```
C:/Users/ks-morozov/.gradle/caches/transforms-3/12a238d05bfa8a9d84c0bcfd6e270869/transformed/jetified-kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.16.
```

if I chang `#distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.3-bin.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip` on 'gradle.propertises'  I get the following error:
```
Some problems were found with the configuration of task ':BlueMS:getDependencies' (type 'DependencyTask').
  - In plugin 'com.google.android.gms.oss-licenses-plugin' type 'com.google.android.gms.oss.licenses.plugin.DependencyTask' field 'configurations' without corresponding getter has been annotated with @Input.
```

what am I doing wrong?

**Comment by adevitturi** [comment]
Hi @hayar2, I ran into the same issue. I could get past it by instead of changing `compileSdkVersion`, by lowering the version of the conflicting dependency instead.
E.g. I changed it to androidx.core:core-ktx:1.5.0 and worked fine for me.

**Comment by ghost** [comment]
@adevitturi thanks a lot, it really works.
