### ISSUE TITLE
Error Build in Android Studio Dolphin

### ISSUE THREAD

**Issue by bloxofcodes** [STMicroelectronics/STBlueMS_Android#18]
Hello Im trying to build the source code but getting below error. I follow the 

[https://github.com/STMicroelectronics/STBlueMS_Android/issues/16#issuecomment-1445707107](url)

But still encountering this error

/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

any ideas or detailed steps to escape from this error?

**Comment by PezzoniL** [comment]
Ciao,
we have just update one full update snapshot of our application removing also the git submodules

please make a check of it:
https://github.com/STMicroelectronics/STBlueMS_Android/tree/FullAppSnapshot
Ciao
