### ISSUE TITLE
How to compile this project on Android Studio?

### ISSUE THREAD

**Issue by Hoools** [STMicroelectronics/STBlueMS_Android#7]
I have Android Studio 3.5.3 and tried several things to run this project, but always got failure. Do you have any description how to compile it ? It can be description for other version of android studio, but then tell me which i should use, please.

**Comment by GiovanniVisentiniST** [comment]
Hi,

what error do you have?

**Comment by Hoools** [comment]
At start of open the project, i got information:
"Unable to get Gradle wrapper properties from: ProjectDir\STBlueMS_Android\gradle\wrapper\gradle-wrapper.properties

Would you like to recreate the wrapper using the latest supported Gradle version?"

When i press the button "Ok", and try to build i got this information:

> Task :BlueMSCloud:compileDebugJavaWithJavac FAILED
STBlueMS_Android\BlueMSCloud\src\main\java\com\st\blesensor\cloud\AwsIot\AwsConfigFragment.java:147: error: cannot find symbol
        mSelectCertificate.setOnClickListener(view ->
                                              ^
  symbol:   method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)
  location: interface LambdaMetafactory
Fatal Error: Unable to find method metafactory

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BlueMSCloud:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 36s




error: cannot find symbol method metafactory(Lookup,String,MethodType,MethodType,MethodHandle,MethodType)

**Comment by Hoools** [comment]
I spend a lot of time yesterday for it. Now i can compile and run this project. The problem was Android SDK which i need to reinstall. Now everything is ok.

But now im sad, because i have STM32WB BLE, and cant discovery him.

I just noticed that in yout google play version 4.6.3 in BLE Toolbox, everything is okay, but in 4.6.1 and 4.6.3 in button ,,Connct to a device" i dont see this device.

It is possible to see at differences BLE Toolbox to Connect to a device? 
On your github branch with version 4.6.3 doesnt exists.

**Comment by GiovanniVisentiniST** [comment]
Hi,

the BLE Toolbox is not public yet.
you can see the device into the "connect to a device" because in that page the device are filtered by theirs advertise value.
you can try with the BLE_HeartRate, BLE_p2pServer or [FP-SNS-MotenvWb](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-ode-function-pack-sw/fp-sns-motenvwb1.html) that has the correct advertise.

**Comment by Hoools** [comment]
Ok, thank you. 

It would be nice if you make the BLE Toolbox public.
